PREFIX bds:  <http://www.bigdata.com/rdf/search#>
PREFIX bioc: <http://www.ldf.fi/schema/bioc/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?occupation ?occupationLabel WHERE {
  ?occupation rdfs:subClassOf+ bioc:Occupation .
  ?occupation rdfs:label ?occupationLabel .
  ?occupationLabel bds:search "{{}}"
  }