SELECT DISTINCT ?id ?p ?name ?type ?typelabel ?pid ?rank ((?score0 *100) AS ?score)
WHERE {
    ?name bds:search "{{q}}" .
    ?name bds:matchAllTerms "true" .
    ?name bds:minRelevance "0.25" .
    ?name bds:relevance ?score0 .
    ?name bds:maxRank "1000" .
    ?name bds:rank ?rank .
    ?id ?p ?name
    {SELECT DISTINCT ?id ?type ?pid ?typelabel 
	    WHERE {
            ?id a ?type
            BIND(REPLACE(str(?type), "(.*)/(.*)$", "$2") AS ?typelabel) .
		    #?id a crm:E53_Place .
		    #?s crm:P1_is_identified_by ?pid .
        }
    }
}
ORDER BY ?rank
LIMIT 100

WHERE {  
{% include 'retrieve_entities_v2.sparql' %}
}