SELECT DISTINCT ?id ?p ?name ?rank ((?score0 *100) AS ?score)
WHERE {
    ?name bds:search "{{q}}" .
    ?name bds:matchAllTerms "true" .
    ?name bds:minRelevance "0.25" .
    ?name bds:relevance ?score0 .
    ?name bds:maxRank "1000" .
    ?name bds:rank ?rank .
    ?id ?p ?name
}
ORDER BY ?rank
LIMIT 100

WHERE {  
{% include 'retrieve_entities_v2.sparql' %}
}