version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        # [Choice] Python version: 3, 3.8, 3.7, 3.6
        VARIANT: "3.10"
        # [Choice] Install Node.js
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        INSTALL_DEV: "true"
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached
      #- /home/sennierer/.ssh:/home/vscode/.ssh:cached

      # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    env_file:
      - development.env
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  db:
    image: nawer/blazegraph
    environment:
      JAVA_XMS: 512m
      JAVA_XMX: 1g
    volumes:
      - ./var/blazegraph:/var/lib/blazegraph
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "9999:9999"

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    network_mode: service:db
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
