version: '3'

services:
  intavia_backend_app:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        # [Choice] Python version: 3, 3.8, 3.7, 3.6
        VARIANT: "3.10"
        # [Choice] Install Node.js
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        INSTALL_DEV: "true"
        USER_UID: 1000
        USER_GID: 1000

      #- /home/sennierer/.ssh:/home/vscode/.ssh:cached

      # Overrides default command so things don't shut down after the process ends.
    # command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
    env_file:
      - development-standalone.env
    
    ports:
      - "5000:5000"

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  db:
    image: lyrasis/blazegraph:2.1.5
    environment:
      JAVA_XMS: 512m
      JAVA_XMX: 1g
    volumes:
      - ./blazegraph/data:/data
      - ./blazegraph/RWStore.properties:/RWStore.properties
    ports:
      - "8889:8889"

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    # network_mode: service:db
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
