{% include 'prefixes_v2_1.sparql' %}

SELECT ?entity ?entityType ?entityTypeLabel ?entityLabel ?gender ?genderLabel ?nationalityLabel ?occupation ?occupationLabel 
?event ?linkedIds ?count ?geometry ?role_type ?mediaObject ?biographyObject

{% include 'add_datasets_v2_1.sparql' %}

WITH {
SELECT DISTINCT ?entity ?entityTypeLabel ?entity_proxy 

{% for dataset in datasets -%}
FROM <{{dataset.value}}>
{% endfor %}

WHERE {
{% include 'bulk_query_entities_v2_1.sparql' %}
{% include 'entity_type_bindings_v2_1.sparql' %}
} ORDER BY ?entity
LIMIT {{limit}}
{% if _offset > 0 %}OFFSET {{_offset}}{% endif %}
} AS %query_set

WITH {
    SELECT (COUNT(DISTINCT ?entity) AS ?count)

    {% include 'add_datasets_v2_1.sparql' %}

    WHERE {
        {% include 'bulk_query_entities_v2_1.sparql' %}
        {% include 'entity_type_bindings_v2_1.sparql' %}
    }
} AS %count_set

WHERE {  
INCLUDE %query_set
INCLUDE %count_set
{% include 'retrieve_entities_v2_1.sparql' %}
}