{% include 'prefixes_v2_1.sparql' %}

SELECT ?event ?role ?entity ?event_label ?role_label ?begin ?end ?time_span_label ?role_type ?event_type ?count

{% include 'add_datasets_v2_1.sparql' %}

WITH {
SELECT DISTINCT ?event 

{% for dataset in datasets -%}
FROM <{{dataset.value}}>
{% endfor %}

WHERE {
{% include 'bulk_query_events_v2_1.sparql' %}
} ORDER BY ?event
LIMIT {{limit}}
{% if _offset > 0 %}OFFSET {{_offset}}{% endif %}
} AS %query_set

WITH {
    SELECT (COUNT(DISTINCT ?event) AS ?count)

    {% include 'add_datasets_v2_1.sparql' %}

    WHERE {
        {% include 'bulk_query_events_v2_1.sparql' %}
    }
} AS %count_set

WHERE {  
INCLUDE %query_set
INCLUDE %count_set
{% include 'retrieve_events_v2_1.sparql' %}
}