{%- if kind -%}
    {%- for k1 in kind -%}
    {?entity a {{k1.get_rdf_uri()}}
    BIND("{{k1}}" AS ?entityTypeLabel)}
        {% if not loop.last %}UNION{% endif %}
    {%- endfor -%}
{%- else -%}
{?entity a idmcore:Person_Proxy 
BIND("person" AS ?entityTypeLabel)
} UNION {
?entity a crm:E74_Group 
BIND("group" AS ?entityTypeLabel)
} UNION {
?entity a crm:E53_Place 
BIND("place" AS ?entityTypeLabel)
} UNION {
    ?entity a idm:CHO_Proxy
    BIND("cultural-heritage-object" AS ?entityTypeLabel)
  }
{%- endif -%}