PREFIX bds:  <http://www.bigdata.com/rdf/search#>
PREFIX bioc: <http://ldf.fi/schema/bioc/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?vocabulary ?vocabulary_label ?related_vocabulary ?relation_type

{% for dataset in datasets %}
FROM <{{dataset.value}}>
{% endfor %}

WHERE {
  BIND(<{{event_role_id}}> as ?vocabulary)
  ?vocabulary rdfs:subClassOf bioc:Event_Role .
  ?vocabulary rdfs:label ?vocabulary_label .
  OPTIONAL{
  	?vocabulary rdfs:subClassOf ?related_vocabulary .
    FILTER(?related_vocabulary != bioc:Event_Role)
    BIND('broader' as ?relation_type)
  }
  }