PREFIX bds:  <http://www.bigdata.com/rdf/search#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX idm: <https://www.intavia.eu/idm/>
PREFIX idmcore: <http://www.intavia.eu/idm-core/>
PREFIX bioc: <http://ldf.fi/schema/bioc/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?entity ?entityType ?entityTypeLabel ?entityLabel ?gender ?genderLabel ?nationalityLabel ?occupation ?occupationLabel 
?event ?eventLabel ?role ?roleLabel ?start ?end ?role_type 
?evPlace ?evPlaceLatLong ?evPlaceLabel ?linkedIds ?count ?geometry

{% for dataset in datasets %}
FROM <{{dataset.value}}>
{% endfor %}

WHERE {
BIND(<{{entity_id}}> as ?entity)
{% include 'entity_type_bindings_v2_1.sparql' %}
{% include 'retrieve_entities_v2_1.sparql' %}
}