{% include 'prefixes_v2_1.sparql' %}

SELECT ?event ?role ?entity ?event_label ?role_label ?begin ?end ?time_span_label ?role_type ?event_type


WHERE {
BIND(<{{event_id}}> as ?event)
{% include 'retrieve_events_v2_1.sparql' %}
}