
{%- if q -%}
?entity crm:P1_is_identified_by ?appellation .
?appellation a crm:E33_E41_Linguistic_Appellation .
?appellation rdfs:label ?entityLabel .
?entityLabel bds:search "{{q}}" .
{%- endif -%}
{%- if occupation -%}
    ?entity bioc:has_occupation ?occupation1 . 
    ?occupation1 rdfs:label ?occupationLabel1 .
    ?occupationLabel1 bds:search "{{occupation}}" .
    ?occupationLabel1 bds:matchAllTerms "true" .
{%- endif -%}
{%- if occupations_id -%}
    {%- for occ in occupations_id -%}
        {?entity bioc:has_occupation <{{occ}}>}
        {% if not loop.last %}UNION{% endif %}
        {%- endfor -%}
{%- endif -%}
{%- if born_before -%}
    ?bornBeforeEvent a crm:E67_Birth .
    ?bornBeforeEvent crm:P98_brought_into_life ?entity .
    ?bornBeforeEvent crm:P4_has_time-span/(crm:P82a_begin_of_the_begin|crm:P82b_end_of_the_end) ?bornBeforeFilter .
    FILTER(?bornBeforeFilter < xsd:dateTime("{{born_before}}"))
{%- endif -%}
{%- if born_after -%}
    ?bornAfterEvent a crm:E67_Birth .
    ?bornAfterEvent crm:P98_brought_into_life ?entity .
    ?bornAfterEvent crm:P4_has_time-span/(crm:P82a_begin_of_the_begin|crm:P82b_end_of_the_end) ?bornAfterFilter .
    FILTER(?bornAfterFilter > xsd:dateTime("{{born_after}}"))
{%- endif -%}
{%- if died_before -%}
    ?diedBeforeEvent a crm:E69_Death .
    ?diedBeforeEvent crm:P100_was_death_of ?entity .
    ?diedBeforeEvent crm:P4_has_time-span/(crm:P82a_begin_of_the_begin|crm:P82b_end_of_the_end) ?diedBeforeFilter .
    FILTER(?diedBeforeFilter < xsd:dateTime("{{died_before}}"))
{%- endif -%}
{%- if died_after -%}
    ?diedAfterEvent a crm:E69_Death .
    ?diedAfterEvent crm:P100_was_death_of ?entity .
    ?diedAfterEvent crm:P4_has_time-span/(crm:P82a_begin_of_the_begin|crm:P82b_end_of_the_end) ?diedAfterFilter .
    FILTER(?diedAfterFilter > xsd:dateTime("{{died_after}}"))
{%- endif -%}
{%- if kind -%}
    {%- for k1 in kind -%}
    {?entity a {{k1.get_rdf_uri()}}}
        {% if not loop.last %}UNION{% endif %}
    {%- endfor -%}
{%- endif -%}
{%- if gender -%}
    ?entity bioc:has_gender|bioc:gender bioc:{{gender.name}} .
{%- endif -%}
{%- if gender_id -%}
    ?entity bioc:has_gender|bioc:gender <{{gender_id}}> .
{%- endif -%}
{%- if related_entity -%}
?entity bioc:bearer_of ?role . ?role ^bioc:had_participant_in_role ?event .
    ?event (crm:P7_took_place_at|(bioc:had_participant_in_role/^bioc:bearer_of)) ?evEntity .  
        {?evEntity crm:P1_is_identified_by ?evEntityAppelation .
                ?evEntityAppelation a crm:E33_E41_Linguistic_Appellation .
                ?evEntityAppelation rdfs:label ?evEntityLabel } UNION {
                    ?evEntity rdfs:label ?evEntityLabel }
    ?evEntityLabel bds:search "{{related_entity}}" .
{%- endif -%}
{%- if related_entities_id -%}
?entity bioc:bearer_of ?role . ?role ^bioc:had_participant_in_role ?event .
    {%- for entity in related_entities_id -%}
        {?event (crm:P7_took_place_at|(bioc:had_participant_in_role/^bioc:bearer_of)) <{{entity}}>}
        {% if not loop.last %}UNION{% endif %}
        {%- endfor -%}
{%- endif -%}
{%- if event_role -%}
?entity bioc:bearer_of ?role .
    ?role a/rdfs:label ?roleLabel .
    ?roleLabel bds:search "{{event_role}}" .
    ?roleLabel bds:matchAllTerms "true" .
{%- endif -%}
{%- if event_roles_id -%}
?entity bioc:bearer_of ?role .
    {%- for role in event_roles_id -%}
        {?role a <{{role}}>}
        {% if not loop.last %}UNION{% endif %}
        {%- endfor -%}
{%- endif -%}