?event a ?event_type .
  ?event ((bioc:had_participant_in_role|bioc:occured_in_the_presence_of_in_role)/^bioc:bearer_of)|crm:P7_took_place_at ?entity_proxy .
  ?entity_proxy idmcore:proxy_for ?entity .
OPTIONAL {?event rdfs:label ?event_label }
OPTIONAL {?event bioc:had_participant_in_role|bioc:occured_in_the_presence_of_in_role ?role .
    ?role ^bioc:bearer_of ?entity_proxy .
    ?role a ?role_type .
    OPTIONAL {?role rdfs:label ?role_label}
  }
  OPTIONAL {?event crm:P7_took_place_at ?entity_proxy .
    ?entity_proxy idmcore:proxy_for ?entity .
    BIND("took place at" as ?role_label)
    BIND(crm:P7_took_place_at as ?role_type)
  }
OPTIONAL {?event crm:P4_has_time-span ?time_span
OPTIONAL {?time_span crm:P82a_begin_of_the_begin ?begin }
OPTIONAL {?time_span crm:P82b_end_of_the_end ?end }
OPTIONAL {?time_span rdfs:label ?time_span_label }
}