BIND("no label provided" AS ?defaultEntityLabel)
OPTIONAL {?entity crm:P1_is_identified_by ?appellation .
{?appellation a crm:E33_E41_Linguistic_Appellation .} UNION {?appellation a crm:E35_Title}
?appellation rdfs:label ?entityLabelPre .}
OPTIONAL {?entity bioc:has_occupation ?occupation . ?occupation rdfs:label ?occupationLabel .}
OPTIONAL {?entity owl:sameAs ?linkedIds}
OPTIONAL {?entity bioc:has_gender ?gender 
    OPTIONAL {?gender rdfs:label ?genderLabel }}
OPTIONAL {?entity bioc:has_nationality ?nationality . ?nationality rdfs:label ?nationalityLabel .}
OPTIONAL {?entity bioc:bearer_of ?role . 
        ?role ^bioc:had_participant_in_role|^bioc:occured_in_the_presence_of_in_role ?event .
        ?role a ?role_type
}
OPTIONAL {?entity crm:P168_place_is_defined_by/crm:P168_place_is_defined_by ?geometry}
OPTIONAL {?entity ^crm:P70_documents ?mediaObject }
BIND(COALESCE(?entityLabelPre, ?defaultEntityLabel) AS ?entityLabel)