?entity crm:P1_is_identified_by ?appellation .
?appellation a crm:E33_E41_Linguistic_Appellation .
?appellation rdfs:label ?entityLabel .
OPTIONAL {?entity bioc:has_occupation ?occupation . ?occupation rdfs:label ?occupationLabel .}
OPTIONAL {?entity owl:sameAs ?linkedIds}
OPTIONAL {?entity bioc:has_gender|bioc2:gender ?gender 
    OPTIONAL {?gender rdfs:label ?genderLabel }}
OPTIONAL {?entity bioc:has_nationality ?nationality . ?nationality rdfs:label ?nationalityLabel .}
OPTIONAL {?entity bioc2:bearer_of ?role . ?role ^bioc2:had_participant_in_role ?event}
OPTIONAL {?entity crm:P168_place_is_defined_by/crm:P168_place_is_defined_by ?geometry}