PREFIX bds:  <http://www.bigdata.com/rdf/search#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX bioc: <http://www.ldf.fi/schema/bioc/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX idm: <https://www.intavia.eu/idm/>
PREFIX idmcore: <http://www.intavia.eu/idm-core/>    

SELECT ?person ?entityType ?entityTypeLabel ?entityLabel ?genderLabel ?nationalityLabel ?occupationLabel ?event ?eventLabel ?role ?roleLabel ?start ?end ?role2 ?roleLabel2 ?entity2 ?entity2Label ?entity2TypeLabel ?entity2Type WHERE {  
?person idmcore:person_proxy_for|idmcore:group_proxy_for ?entity .
?person crm:P1_is_identified_by ?appellation .
?entity a ?entityType .
?appellation a crm:E33_E41_Linguistic_Appellation .
?appellation rdfs:label ?entityLabel .
?entityLabel bds:search "{{q}}"
BIND (IF(?entityType = <http://www.intavia.eu/idm-core/Provided_Person>, "person", IF(?entityType = <http://www.intavia.eu/idm-core/Provided_Group>, "group", IF(?entityType = <http://www.cidoc-crm.org/cidoc-crm/E53_Place>, "place", "entity"))) AS ?entityTypeLabel)
OPTIONAL {?person bioc:has_occupation ?occupation . ?occupation rdfs:label ?occupationLabel .}
OPTIONAL {?person bioc:has_gender ?gender . ?gender rdfs:label ?genderLabel .}
OPTIONAL {?person bioc:has_nationality ?nationality . ?nationality rdfs:label ?nationalityLabel .}
OPTIONAL {?person ^crm:P98_brought_into_life/crm:P4_has_time-span/crm:P81a_begin_of_the_begin ?dateOfBirth .}
OPTIONAL {?person ^crm:P100_was_death_of/crm:P4_has_time-span/crm:P81a_begin_of_the_begin ?dateOfDeath .}
OPTIONAL {?person idmcore:inheres_in ?role . ?role ^idmcore:had_participant_in_role ?event 
    OPTIONAL{?role rdfs:label ?roleLabel} 
    OPTIONAL {?event rdfs:label ?eventLabel} 
    OPTIONAL {?event crm:P4_has_time-span/crm:P82a_begin_of_the_begin ?start} 
    OPTIONAL {?event crm:P4_has_time-span/crm:P82b_end_of_the_end ?end} 
    OPTIONAL {?event idmcore:had_participant_in_role ?role2 . ?role2 ^idmcore:inheres_in ?entity2 
      OPTIONAL{?role2 rdfs:label ?roleLabel2}  
      OPTIONAL{?entity2 crm:P1_is_identified_by ?entity2LabelID . ?entity2LabelID rdfs:label ?entity2Label; a crm:E33_E41_Linguistic_Appellation}
      OPTIONAL{?entity2 idmcore:group_proxy_for ?providedEntity2 . ?providedEntity2 a ?entityType2} 
      OPTIONAL{?entity2 idmcore:person_proxy_for ?providedEntity2 . ?providedEntity2 a ?entityType2} 
      FILTER(?person != ?entity2)}}
BIND (IF(?entityType2 = <http://www.intavia.eu/idm-core/Provided_Person>, "person", IF(?entityType2 = <http://www.intavia.eu/idm-core/Provided_Group>, "group", IF(?entityType2 = <http://www.cidoc-crm.org/cidoc-crm/E53_Place>, "place", "entity"))) AS ?entity2TypeLabel)
}