{% include 'prefixes_v2_1.sparql' %}

SELECT ?occupation (COUNT(DISTINCT ?entity) as ?count) ?occupationLabel ?broaderUri ?broaderLabel
WHERE {

?entity a idmcore:Person_Proxy .
?entity bioc:has_occupation ?occupation .
?occupation rdfs:label ?occupationLabel .
OPTIONAl {
    ?occupation rdfs:subClassOf ?broaderUri .
    ?broaderUri rdfs:label ?broaderLabel
}
    {% if ids %}{% include 'bulk_query_entities_v2_1.sparql' %}{% else %}
    {% include 'query_entities_v2_1.sparql' %}{% endif %}
}
GROUP BY ?occupation ?occupationLabel ?broaderUri ?broaderLabel
